# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Self Hosted Agent'

variables:
  imageName: 'portfolio'  # Replace with your Docker image name
  tag: '$(Build.BuildId)'  # Use the build ID as the image tag

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'container-registry-svcon'  # Replace with your ACR service connection name
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - script: |
        echo "Build ID: $(Build.BuildId)"
        echo "Tag: $tag"
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
