trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - manifests/**

pool:
  name: 'Self Hosted Agent'

variables:
  imageName: 'portfolio'  # Replace with your Docker image name
  tag: '$(Build.BuildId)'  # Use the build ID as the image tag

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'container-registry-svcon'  # Replace with your ACR service connection name
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - script: |
        echo "Build ID: $(Build.BuildId)"
        echo "Tag: $(tag)"
        
    - script: |
        sed -i 's|image:.*|image: acrprivateshubh.azurecr.io/portfolio:$(Build.BuildId)|' manifests/Deployment.yaml
      displayName: 'Update image in Deployment.yaml'

    - script: |
        git config --global user.email "$(Build.RequestedForEmail)"
        git config --global user.name "$(Build.RequestedFor)"
        git add .
        git commit -m "Update image to acrprivateshubh.azurecr.io/portfolio:$(Build.BuildId)"
        git push https://$(System.AccessToken)@dev.azure.com/shubhamhadgal/_git/Private-K8s HEAD:$(Build.SourceBranchName)
      displayName: 'Commit and push changes'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
