apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  # pod def
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
      - name: portfolio-img-pull-secret
      containers:
      - name: portfolio
        image: acrprivateshubh.azurecr.io/portfolio:213
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
# 