apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-green
  namespace: go-green
spec:
  selector:
    matchLabels:
      app: go-green
  # pod def
  template:
    metadata:
      labels:
        app: go-green
    spec:
      imagePullSecrets:
      - name: gogreen-img-pull-secret
      containers:
      - name: go-green
        image: acrprivateshubh.azurecr.io/green:336
        resources:
          requests: 
            memory: 32Mi
            cpu: "5m"
          limits:
            memory: "64Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
