apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-green-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-green
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
